### ISSUE TITLE
The error in parsing a Date field increases by 1 year

### ISSUE THREAD

**Issue by trngqu4nutc** [oryanmoshe/debezium-timestamp-converter#22]
Hi,
I encountered a parsing error with a Date field increasing by 1 year.
example: value "2022-12-31" will result in "2023-12-31", similarly with the end dates of December from 27-31 will encounter the same error.

**Comment by rgriffogoes** [comment]
@trngqu4nutc Sorry for bringing this up, but do you recall what you had to do to fix this issue?

**Comment by rgriffogoes** [comment]
For future reference, using parameters like below can "fix" the issue:

    timestampConverter.format.date": "yyyy-MM-dd

There are pull request and other forks where the default format string is adjusted.

For example https://github.com/dz902/debezium-timestamp-converter
